- manifests/credentials.pp
- manifests/init.pp
- manifests/params.pp
- manifests/security.pp
- manifests/user.pp
Puppet modules fails while modifying users, credentials or security when the server is not yet up. This PR implements timeouts.
> fixes timeouts on restart

- metadata.json
Puppet Forge has been marking the mechanical metadate score down because
of issues with the metadata.json
This change cleans up the project page URL so that it is verifiable and
will actually work correctly when clicking on the link from Puppet Forge
This change modifies the license clause to be SPDX compliant
This change adds bounds to the dependencies as having unbounded ranges
lowers the score. The current bounds should be large enough to handle
future versions properly for at least a little while.
Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>
> Cleanup metadata.json for better mechanical score

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
Currently, the creation of jenkins user
and group is protected by if !defined. This
can be extremely annoying in cases where code
is trying to install a competing jenkins user/group.
In my specific case, I'm blocked by this code
leading to duplicate jenkins users (and I need
my definition to be created first). In general,
I thought that these kinds of issue were resolvable
via enusre that classes were including in a certain
order, but I cannot seem to resove it in my specific use
case which involves:
* nested class includes
* serialized user resources from hiera
* create_resources
> Make creation of user optional

- HACKING.md
Lets make @rtyler happy! :smile:
> Add instructions for acceptance tests

- .fixtures.yml
The 2.0.0 release of puppetlabs-apt includes major breaking changes to the API.
The metadata.json already specifies puppetlabs-apt as < 2.0 but the fixtures
version was free floating.
> pin puppetlabs-apt fixtures version to 1.8.0

- manifests/repo/debian.pp
Since a few days puppetlabs/apt module throw a warnings if a full fingerprint
is not used.
> Change apt key to full fingerprint

- manifests/job/absent.pp
- manifests/job/present.pp
Escape names when using the CLI to create or remove jobs.
This allows job names s to contain spaces, brackets and braces.
> Escape job names for shell commands

- .fixtures.yml
- README.md
- manifests/config.pp
- manifests/direct_download.pp
- manifests/init.pp
- manifests/package.pp
- manifests/params.pp
- metadata.json
- spec/classes/jenkins_direct_download_spec.rb
Hi There,
Thanks for your hard work on this package.  I've developed a PR you may be interested in which adds support for directly downloading the RPM package from a regular HTTP server.
This is useful for places that both don't have their own yum repository or access to download from the Internet.
The PR works by adding a new parameter to the `jenkins` class called `direct_download` which the user can use to specify the whole remote path to the package file which can then be downloaded and installed.
I've also fully documented this, added an RSpec test class, added this new class into the anchors your using and fixed the metadata.json file (there were invalid version numbers and I'm using `nanlui/staging` to download remote files).
Hope this can be merged if at all possible.
Thanks, …
> Direct package

- metadata.json
To allow usage of validate_integer()
> change puppetlabs/stdlib version dep to >= 4.6.0

- manifests/cli_helper.pp
If $ssh_keyfile was not specified, an extra two spaces would appear in
$helper_cmd.  This was harmless but annoying when unit testing the value of
that variable.
> remove unnecessary whitespace from $::jenkins::cli_helper::helper_cmd

- Gemfile
The 'jenkins-infra/puppetlabs_spec_helper' fork is significantly behind the
mainline gem release.
> use mainline puppetlabs_spec_helper gem

- spec/spec_helper_acceptance.rb
Resolves this error:
/home/jhoblitt/github/puppet-jenkins/.bundle/ruby/2.1.0/gems/beaker-2.7.1/lib/beaker/host.rb:378:in `exec': Host 'ubuntu-server-12042-x64' exited with 1 running: (Beaker::Host::CommandFailure)
puppet module install puppetlabs-stdlib --version >= 2.0.0
Last 10 lines of output were:
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
(at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Error: Could not install module 'puppetlabs-stdlib' (???)
No version of 'puppetlabs-stdlib' can satisfy all dependencies
Use `puppet module install --ignore-dependencies` to install only this module
> remove puppet module versions constraints from beaker setup

- Gemfile
beaker-rspec 5 requires rspec >= 3
> remove rspec gem ~> 2.99.0 constraint

- .travis.yml
To reduce wall clock CI execution time.
> remove puppet > 3 < 3.6 from travis matrix

- README.md
- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
Direct URL from which to download plugin without modification.  This is
particularly useful for development and testing of plugins which may not be
hosted in the typical Jenkins' plugin directory structure.
> add source parameter to jenkins::plugin define

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
As $plugin_dir has its ownership management, it should always be safe to run the exec resources in this define as the same user.  This eliminates superfluous file permission change notifications from the log output.  E.g.,
==> master: Notice: /Stage[main]/Main/Jenkins::Plugin[mailer]/File[/var/lib/jenkins/plugins/mailer.hpi]/owner: owner changed 'root' to 'jenkins'
> set user on exec resources in jenkins::plugin define

- manifests/job.pp
- spec/defines/jenkins_job_spec.rb
- spec/fixtures/testjob.xml
This is a new PR to replace #257 whose repo has now been deleted and replaced. The new code should be a little more elegant, and now contains rspec tests.
Cheers,
Gavin.
> Support getting external .xml job descriptions

- manifests/init.pp
- manifests/users.pp
- spec/classes/jenkins_users_spec.rb
Similar to the jenkins::jobs class that declares all instances of
the jenkins::job defined type, the jenkins::users class declares all
instances of the jenkins::user defined type. I added it to the
main jenkins class with a user_hash parameter.
> Add jenkins::users class to declare all users

- manifests/security.pp
Commit 6bc33de changed a whole bunch of `exec`s to `jenkins::cli::exec`
but missed this one out.
Without this change `exec` gets grumpy about the `command` argument
being an array.
> Use jenkins::cli::exec in security.pp

- manifests/plugin.pp
It was hardcoded in at least these two occurrences.
> Package name no longer hardcoded

- .fixtures.yml
- metadata.json
This supersedes #301.
When they released the v2.0 version of the apt module, the folks at Pupperlabs also broke backwards compatibility. This caused a lot of problems, so they've gone back and released a v2.1 that adds support for the v1 way of doing things.
What this means is that it's better so support the old way of doing things than the new way, as the old way has the largest compatibility spread. In my previous pull request (which was made before the apt v2.1 release was made) I attempted to support both version of the module, but this accomplishes that much better.
There is one caveat though- this module will not support v2.0 of the apt module, and unfortunately there is no way to exclude specific versions of dependencies in the metadata.json file. This means there's no way to …
> Upgraded apt module dependency to support v2

- manifests/init.pp
- manifests/repo/el.pp
- spec/classes/jenkins_repo_el_spec.rb
This pull request adds a new parameter yum_proxy to init.pp. It's used in repo/el.pp to configure the jenkins yum repository with a proxy server. 
This allows installing jenkins via yum behind a proxy server.
> Support configuring a yum proxy server

- manifests/plugin.pp
We have setup with jenkins running under tomcat (user tomcat7), but still it is good idea to have Jenkins files in /var/lib/jenkins.
This patch fixes plugin installation in this use-case - with external user already created and also when it is different from /var/lib/jenkins owner.
(this is fixed pull request #333)
> Fix jenkins::plugin with create_user false

- manifests/job/present.pp
Hi,
I ran into timing issues when using the job creation functionality. I've made the retry settings in the job config configurable by using the retry parameters from the global config.
> Set retries in job configuration to global parameters

- manifests/job/present.pp
The class jenkins::job:present is not able to find the class jenkins::cli::reload to run the reload-jenkins exec when using a  pre-built config file in a jenkins::job_hash.
> Class cannot find exec in jenkins::cli::reload.

- manifests/cli.pp
- manifests/init.pp
- spec/classes/jenkins_cli_spec.rb
Greetings! This patch allows the user to specify a key when issuing cli commands. This will prevent things like jenkins::cli::reload from being run as the anonymous user, which breaks if you want to use a restrictive permission scheme.
This might also solve https://github.com/jenkinsci/puppet-jenkins/issues/259.
> Adding cli_ssh_keyfile parameter to specify the location of a private key

- files/puppet_helper.groovy
- manifests/init.pp
- spec/acceptance/class_spec.rb
- spec/classes/jenkins_spec.rb
* add get_slaveagent_port()/set_slaveagent_port() methods to puppet_helper
* add slaveagentport param to jenkins class
> Puppet helper slaveagentport

- README.md
- files/puppet_helper.groovy
- manifests/credentials.pp
- spec/defines/jenkins_credentials_spec.rb
This addresses #226 - It's largely influenced by the Opscode jenkins module, which has this functionality - https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/credentials.rb
> Add parameter to set user uuid in jenkins::credentials define

- lib/puppet/parser/functions/jenkins_prefix.rb
- manifests/cli.pp
- manifests/cli_helper.pp
- manifests/params.pp
- spec/functions/jenkins_prefix_spec.rb
https://github.com/jenkinsci/puppet-jenkins/issues/357
> Added jenkins_prefix function to retrieve configured prefix

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
- templates/org.jenkins-ci.slave.jnlp.plist.erb
- templates/start-slave.sh.erb
This utilizes the existing defaults file, along with a wrapper script and launchd service. There is no wget by default on OSX so use curl there (could be used everywhere, or instead use a puppet module such as archive).
> add darwin/osx support to slave class

- lib/facter/jenkins.rb
- lib/puppet/jenkins/facts.rb
- lib/puppet/jenkins/plugins.rb
This fixes the `require` paths on Ruby 1.8.7 with Puppet 2.7. See issue #132.
> Fix require paths

- spec/classes/jenkins_direct_download_spec.rb
- spec/classes/jenkins_jobs_spec.rb
Resolves this warning:
WARNING: Using the `raise_error` matcher without providing a specific
error or message risks false positives, since `raise_error` will match
when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`,
potentially allowing the expectation to pass without even executing the
method you are intending to call. Instead consider providing a specific
error class or message. This message can be supressed by setting:
`RSpec::Expectations.configuration.warn_about_potential_false_positives
= false`.
> fix rspec-puppet `raise_error` warning

- manifests/job.pp
- spec/defines/jenkins_job_spec.rb
I propose this improvement to add an option to avoid copy/paste files.
Very helpfull when we use something like:
```puppet
$jobs = hiera('jenkins::jobs')
create_resources(jenkins::job, $jobs)
```
And a hiera like this one:
```yaml
jenkins::jobs :
petclinic-build:
jobname: 'petclinic-build'
config: ''
source: 'g10b/petclinic-build.xml'
```
> Add template in the jenkins::job

- spec/acceptance/class_spec.rb
> fix acceptance test path prefix for jenkins-cli.jar

- manifests/slave.pp
- spec/classes/jenkins_direct_download_spec.rb
- spec/classes/jenkins_jobs_spec.rb
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
> [puppet-jenkins#366] Replace -toolLocations with --toolLocation

- files/jenkins-slave.RedHat
(First pull request, please be gentle)
Related to issue #225
This change makes the init script work on CentOS-5.x - or really any host using bash less than version 4.0. This is the original error I was receiving:
```
Starting Jenkins Slave...
-bash: -c: line 0: syntax error near unexpected token `>'
-bash: -c: line 0: `/usr/bin/java  -jar /home/jenkins-slave/swarm-client-1.22-jar-with-dependencies.jar -mode normal -executors 1  -name <redacted> -master <redacted> -labels '<redacted>' -fsroot '/home/jenkins-slave'  &>> /var/log/jenkins-slave/jenkins-slave.log &'
```
This change is more portable than the original command line. So even if this project doesn't want to support CentOS-5.x, this change still guards against shell "gotchas" like this.
> Update jenkins-slave.RedHat init.d script work bash < 4.0

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
There were two orthogonal resource chains for handling plugins with with
the .hpi & .jpi extension.  This commit unifies the two code paths.  It
should fix the resource ordering problem that causes it to take two runs
to install a plugin and pin it.
resolves #380
> remove seperate resources for handling plugin extension

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
`jenkins::slave` uses the `daemon` package on debian.  As this is a
commonly needed package, directly declaring a package resource may lead
to manifest conflicts.
closes #377
> use ensure_packages() to manage the daemon package

- manifests/cli_helper.pp
- manifests/config.pp
- manifests/init.pp
- manifests/job/absent.pp
- manifests/job/present.pp
- manifests/params.pp
- manifests/plugin.pp
- manifests/proxy.pp
- spec/classes/jenkins_cli_helper_spec.rb
- spec/classes/jenkins_master_spec.rb
- spec/classes/jenkins_proxy_spec.rb
- spec/classes/jenkins_spec.rb
- spec/defines/jenkins_plugin_spec.rb
* add `manager_user`, `user`, `manage_group`, `group` params to
`jenkins` class.
* improve consistency of `file` resouce group ownership throughout
the module
* add 'localstatedir' param to `jenkins` class and consistently use it
to set the 'data' base dir throughout the module
* Deprecate/noop `username`, `group`, `create_user` params to
`jenkins::plugin` define; replaced by `user`,`group`,etc. params to
`jenkins` class
* Deprecate/noop `plugin_dir` param to `jenkins::plugin`; replaced by
`localstatedir` param to `jenkins` class
closes #356 -- alternative approach
resolves #362
resolves #365
resolves #219 
resolves #249
resolves #250
> add user/group mgt. + localstatedir params to jenkins class

- NATIVE_TYPES_AND_PROVIDERS.md
- README.md
> document types and providers puppetserver known issues

- manifests/slave.pp
This PR intends to give the possibility to change it
> client_url is hardcoded in slave.pp

- manifests/job/present.pp
This seems to be just a minor typo, but it causes create job exec statements to fail the second time, since puppet would retry creating jobs. It cannot find the correct files because of the incomplete path.
> fix job_dir variable reference to jenkins class

- manifests/slave.pp
Hello,
Please find here two commits.
One is forcing the jenkins to be created as a "system" user.
The second is allowing to disable the download of the .jar file to allow installing it using a system package
> Add manage_client_jar option

- manifests/plugin.pp
When the manifest is applied, the jenkins::plugin logs a warning message about `create_user` being deprecated. Since it has no effect (according to the warning), I've switched its default value over to undef from true. This prevents the warning.
> Undefine create_user in plugins

- manifests/cli/config.pp
The main motivation for this is handling the retries gem installation when it is already defined in the catalog. 
This is needed if one has to use a different provider. For example for Puppet 4 to install the retries gem successfully one needs to use the 'puppet_gem' provider. 
Alternative solution would be to handle this in the module directly.
> Check if the retries gem is not already declared

- manifests/cli_helper.pp
Currently, we need to define the ssh_keyfile in two locations: cli.pp and cli_helper.pp. My current hiera yaml file needs both of the following entries to work correctly:
jenkins::cli_helper::ssh_keyfile: '/var/lib/jenkins/.ssh/id_rsa'
jenkins::cli_ssh_keyfile: '/var/lib/jenkins/.ssh/id_rsa'
This change will make the first entry unnecessary.
> Unify the ssh_keyfile

- README.md
- manifests/plugin.pp
When downloading large plugins, it can timeout (e.g. ruby-runtime). The
archive::download supports a timeout value which defaults to 120
seconds, but this plugin class doesn’t have any support to override
this value. This allows for the ability to adjust the timeout value for
large plugins.
Error message when download timeout exceeds 120 seconds:
Error:
/Stage[main]/Jenkins::Plugins/Jenkins::Plugin[ruby-runtime]/Archive::Dow
nload[ruby-runtime.hpi]/Exec[download archive ruby-runtime.hpi and
check sum]/returns: change from notrun to 0 failed: Command exceeded
timeout
> Fix Plugin Download Timeout

- manifests/plugin.pp
The `verbose` attribute of the `archive::download` resource defaults to `true`.
This causes a notice message, `no checksum for this archive`, to be spammed to the terminal when `archive::download` is called without setting the checksum attribute.
This PR suppresses this notice.
> Suppress notice messages when using archive::download

- .travis.yml
Removing unnecessary gem deps should save some CI execution time.
> travis does not need the :system_tests group

- README.md
Fixes a documentation bug concerning the $::jenkins::cli_ssh_keyfile parameter.
> Clarify documention for cli_ssh_keyfile param.

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/jenkins_spec.rb
* add `manage_localstatedir` param to `jenkins class
* align params on equal sign.
* validate that manage_localstatedir is a bool.
* add documentation for manage_localstatedir.
When localstatedir is a symlink to a mount, the user may want to manage that outside of this module.
> Allow the user to manage the localstatedir themselves.

- lib/facter/jenkins.rb
This change fixes this error:
$ puppet agent -t
Info: Loading facts
Error loading fact /usr/local/lib/site_ruby/facter/jenkins.rb: No such file or directory -- /usr/local/lib/site_ruby/puppet/jenkins/facts.rb
Error loading fact /usr/local/lib/site_ruby/facter/jenkins.rb: No such file or directory -- /usr/local/lib/site_ruby/puppet/jenkins/facts.rb
Error loading fact /usr/local/lib/site_ruby/facter/jenkins.rb: No such file or directory -- /usr/local/lib/site_ruby/puppet/jenkins/facts.rb
Error loading fact /usr/local/lib/site_ruby/facter/jenkins.rb: No such file or directory -- /usr/local/lib/site_ruby/puppet/jenkins/facts.rb
Error loading fact /usr/local/lib/site_ruby/facter/jenkins.rb: No such file or directory -- /usr/local/lib/site_ruby/puppet/jenkins/facts.rb
Error loading fact …
> Fix for the jenkins.rb facter error

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
Hi
This fix for https://github.com/jenkinsci/puppet-jenkins/issues/465 actually seems *too* simple.  It works for me, but I suspect I'm missing something! :)
But without an 'ensure' property, what did the file resource actually do?  Chown files if they happened to exist?
Kind Regards,
Alex
> Add ensure=>file to pinning file

- lib/puppet_x/jenkins/type/cli.rb
- spec/unit/puppet_x/spec_jenkins_types.rb
Resolves this ordering error where the type attempts to run before the
CLI jar resource has been converted.
==> master: Error: Could not prefetch jenkins_security_realm provider
'cli': Execution of '/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s
http://localhost:8080 groovy /usr/lib/jenkins/puppet_helper.groovy
get_security_realm' returned 1: Error: Unable to access jarfile
/usr/lib/jenkins/jenkins-cli.jar
> autorequire cli_jar from all PX::J::Type::Cli based types

- README.md
- manifests/init.pp
- spec/classes/jenkins_cli_spec.rb
- spec/classes/jenkins_spec.rb
+ make true the default value of the `jenkins` class `cli` param
This modules uses the cli jar + groovy helper for many of its'
management functions and is currently relying on these to be
automatically included by dependent resources.  For most use cases of
this module, the cli jar + groovy helper are automatically installed
regardless of the value of the `cli` param.  However, this does not
work for the experimental native types which are dependent on the cli
jar and groovy helper.
> enable install of cli_helper when jenkins::cli => true

- files/puppet_helper.groovy
Use case:
We use the jenkins_job to create a "seed" job which calls some groovy scripts
which are responsible for the actual build jobs creation.
[Job DSL plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin).
Part of this DSL are folders, supported by the Cloudbees folder plugin.
Folders however are currently not supported by `puppet_helper.groovy`. When
folders are added the following exception is thrown
```bash
Error: Failed to apply catalog: Execution of '/bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 -i /kvk/.ssh/id_rsa groovy /usr/lib/jenkins/puppet_helper.groovy job_enabled monitoring' r
eturned 255: Unexpected exception occurred while performing groovy command!
groovy.lang.MissingMethodException: No signature of method: …
```
> Add folder support to puppet_helper

- NATIVE_TYPES_AND_PROVIDERS.md
- lib/puppet_x/jenkins/config.rb
- lib/puppet_x/jenkins/provider/cli.rb
- manifests/cli/config.pp
- spec/classes/cli/config_spec.rb
- spec/unit/puppet_x/jenkins/config_spec.rb
- spec/unit/puppet_x/jenkins/provider/cli_spec.rb
This change adds a prefix configration to the jenkins::cli::config class. The prefix is then used in the CLI command to connect to a Jenkins servers which has a prefix configured (in the config_hash).
> Add support for prefix configuration in the CLI config class.

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
It was possible for a plugin to fail to be installed if it's name and
version matched as a substring of an already installed plugin. Which
means that a test for `credentials 1.12` could potentially match on an
incorrect plugin name such as `ssh-credentials 1.12`.
resolves #513
> fix plugin install logic matching

- .fixtures.yml
- manifests/direct_download.pp
- manifests/init.pp
- manifests/plugin.pp
- manifests/slave.pp
- metadata.json
- spec/classes/jenkins_direct_download_spec.rb
- spec/classes/jenkins_slave_spec.rb
- spec/defines/jenkins_plugin_spec.rb
- spec/spec_helper.rb
Replaces the use of:
- `camptocamp/archive`
- `nanliu/staging`
- `exec` resources using `wget` or `curl`
closes #340 (supersedes)
resolves #427
closes #433 (supersedes)
resolves #505
possibly related to #512
> use puppet/archive for all file downloads

- manifests/cli/config.pp
- spec/classes/cli/config_spec.rb
`jenkins::cli::config` currently installs the `retries` gem needed by
the xtypes as a convenience -- it is not clear if functionality should be
in this class at all or if it should merely be a vehicle for passing
data into the catalog.  Puppetserver users will still have to manually
install the `retries` gem as there is no reliable way to determine if an
agent run is configuring a puppet master.
resolves #434 
resolves #498
> attempt to determine the correct gem provider

- lib/puppet/type/jenkins_job.rb
- spec/unit/puppet/type/jenkins_job_spec.rb
If the resource name contains slashes, treat them as a
`cloudbees-folder` path and autorequire all parent folders.
Eg., `foo/bar/myjob` would autorequire the `jenkins_job` resources named
`foo` and `foo/bar`.
relates to #472
> make jenkins_job type cloudbees-folder aware

- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/provider/jenkins_job/cli.rb
- lib/puppet/type/jenkins_job.rb
- spec/acceptance/job_spec.rb
- spec/acceptance/xtypes/jenkins_job_spec.rb
- spec/unit/puppet/provider/jenkins_job/cli_spec.rb
- spec/unit/puppet/type/jenkins_job_spec.rb
- spec/unit/puppet_x/spec_jenkins_types.rb
Special thanks to @damoxc for a lot of hard work on this implementation.
* a `show_diff` parameter to enable/suppress logging of a jobs XML
`config`.  This follows the same semantics as the core `file` type and
required that the agent has `--show-diff` enabled.
* changes to `config` are now logged in unified diff format
* all jobs are prefeteched from a single `puppet_helper.groovy` method, greatly
reducing run time with even a moderate number of jobs.
* compatibility with the `cloudbees-folder` plugin
* basic beaker acceptance tests
closes #418
resolves #541
> multiple jenkins_job type improvements

- files/puppet_helper.groovy
Instead of special casing classes which are known not to respond to the
`isDisabled()` method, use introspection.
resolves #551
> test if job class responds to #isDisabled in job_list_json

- files/puppet_helper.groovy
Looking at this the 5th parameter is the server string not the GroupLookupStrategy.
The arguments only seem to be taking 5 parameters even though it seems from the init (https://github.com/jenkinsci/active-directory-plugin/blob/8a86022e18cb81dd4bc0e7ae9afd5a8cf048d894/src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java#L146) that it might be able to take 6 (https://github.com/jenkinsci/active-directory-plugin/blob/8a86022e18cb81dd4bc0e7ae9afd5a8cf048d894/src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java#L146-L150).
> 5th parameter is server list for ActiveDirectory

- files/jenkins-slave.RedHat
Corrects the path of the lock file for the operating system to wait for the finalization of the Jenkins case before hanging up.
> Fix path LOCK_FILE

- .rubocop.yml
Warning: Deprecated pattern style '/home/jhoblitt/github/puppet-jenkins/spec/fixtures/**' in /home/jhoblitt/github/puppet-jenkins/.rubocop.yml. Change to '/home/jhoblitt/github/puppet-jenkins/spec/fixtures/**/*'.
> fix rubocop conf path syntax warning

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
For some reason, the maintainers of the jenkins "Build Monitoring Plugin" (https://wiki.jenkins-ci.org/display/JENKINS/Build+Monitor+Plugin) decided to put a "+" in their version names (e.g., "1.9+build.201606052339"). This confuses the logic that uses grep to search for installed plugins. The "+" is interpreted as a special regexp character, so no match is found, and puppet tries to install the plugin (and restart jenkins) over and over again. This fix escapes +'s in the search string before it's passed to grep.
> Escape +'s when grepping through jenkins plugin version numbers

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
This change will allow users to use 'jenkins::slave::java_args' as a string, or array. With support for hiera_array merging; based on hiera config.
> -- #573: Convert jenkins::slave::java_args to support both strings and arrays.

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
The `jenkins` and `jenkins::slave` classes should be fully decoupled so
that the `jenkins` class is not required to be in the catalog for a
"slave only" node.
> add 'proxy_server' param to jenkins::slave class

- templates/jenkins-slave-defaults.erb
#367 introduced single quotes.  Can't work for multiple tool_locations in the current state since only the last statement will get used.
> Fix tool_locations bash via doublequotes

- Gemfile
2.0.1 requires Ruby version: >= 0
2.0.2 requires Ruby version: ~> 2.0
FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
https://twitter.com/agentdero/status/765587955612160001
> Pin the loose dependency (from hiera) on json_pure to something less than 2.0.2

- manifests/slave.pp
maven.jenkins-ci.org has been deprecated and redirecting to repo.jenkins-ci.org for *years*
> Use a up-to-date swarm client URL

- manifests/direct_download.pp
- manifests/init.pp
- manifests/plugin.pp
- manifests/proxy.pp
- spec/classes/jenkins_proxy_spec.rb
- spec/classes/jenkins_spec.rb
These changes avoid one or many warnings:
Warning: Undefined variable 'proxy_server'; 
(file & line not available)
...from direct_download.pp and plugin.pp. I was seeing warnings from direct_download.pp when using direct_download but not using a proxy. I'm using puppet 4.7.0.
> Avoid "Undefined variable 'proxy_server'" warnings.

- manifests/plugin.pp
This change brings the regex pattern for plugin (without version) search inline with the regex pattern for plugin+version search on line 80.
Without the prepended caret (^), plugins that are not installed may fail to install due to false positives.  Example:
* Install the `ssh-credentials` plugin
* Install the `credentials` plugin
With the current logic, the regex "credentials" will match the existing plugin "ssh-credentials" and the plugin will not be installed.  Adding a ^ fixes this issue.
> Plugins fail to install due to search false positives

- Gemfile
- Rakefile
This platform locks parallel_tests so only newer Rubies can make use of it, yey
> Newer versions of parallel_tests require Ruby 2.0 or newer

- README.md
your readme missing to inform user to also include puppetlabs firewall module when `configure_firewall => true` is declared
> add firewall module dependency info

- files/puppet_helper.groovy
Add gitlab token api credential to switch statement for
credentials_list_json in the puppet_helper.groovy script.
Without this, the credentials native type fails with an
unsupported credentials error if you have a gitlab api
token in your credentials list.
> Add support for gitlab api token credential - #664

- manifests/cli.pp
- manifests/init.pp
- spec/classes/jenkins_spec.rb
This is especially useful when deploying Jenkins from a Docker container, but
still wishing to use some of the great abstractions around job/user/etc
management in this module.
This doesn't change the expectation that /something/ will implement
Service[jenkins] in the catalog, as that would make the implementation of types
like jenkins::cli::exec obscenely complex (and maybe not even possible).
> Add support for disabling management of Service[jenkins]

- files/jenkins-slave.Debian
grep with full-format listing can cause collisions with
other processes with java/daemon in their process args.
> Fix get_running issue for jenkins slave

- manifests/init.pp
- manifests/params.pp
- manifests/slave.pp
- manifests/sysconfig.pp
- spec/acceptance/class_spec.rb
- spec/acceptance/slave_spec.rb
- spec/classes/jenkins_spec.rb
- spec/defines/jenkins_sysconfig_spec.rb
- spec/spec_helper_acceptance.rb
Controls the path to the "sysconfig" file that stores jenkins service
startup variables
> add ::jenkins::sysconfdir parameter

- .fixtures.yml
- manifests/slave.pp
- metadata.json
- spec/acceptance/slave_spec.rb
- spec/classes/jenkins_slave_spec.rb
- spec/spec_helper_acceptance.rb
- templates/jenkins-slave.service.erb
Due to fact quoting shenanigans, systemd support wasn't working. Due to the same logic error in the acceptance tests, systemd wasn't being properly covered either.
Resolves #663
> fix slave systemd support

- manifests/config.pp
- manifests/init.pp
- spec/classes/jenkins_spec.rb
mash up of #646 and #675
Allows the version of the credentials plugin to be specified via plugin_hash by removing it from the default_plugins list.  Eg.  (Per @jeffmccune)
jenkins::default_plugins: []
jenkins::plugin_hash:
credentials:
version: 2.1.5
digest_string: 7db002e7b053f863e2ce96fb58abb98a9c01b09c
digest_type: sha1
closes #646
closes #675
resolves #665
> add jenkins::default_plugins param

- manifests/config.pp
- spec/classes/jenkins_spec.rb
Without a restart, a jenkins fault may occur when listing installed
plugins as the plugin may still be loaded but the persistent files would
be absent from disk.
> restart jenkins master after purging plugins

- manifests/slave.pp
It looks like the java_version parameter for the jenkins::slave class is not used. This removes its documentation to reflect reality.
> Remove doc string for unused java_version param

- NATIVE_TYPES_AND_PROVIDERS.md
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/type/jenkins_credentials.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
These are needed for jenkins to integrate with the phabricator plugin.
> Add support for conduit credentials

- NATIVE_TYPES_AND_PROVIDERS.md
Small typo in native types and providers docs prevented `jenkins_job` being readable...
> (documentation) [ci skip]: minor typo affecting markdown rendering of jenkins_job

- manifests/plugin.pp
Without this change, our integration testing fails on the idempotence check: the plugin download files aren't set to the correct ownerships on the initial run, and are restored on the second run:
```
Notice: Compiled catalog for 1a6e30201881 in environment production in 4.64 seconds
Info: Applying configuration version '1495173361'
Notice: /Stage[main]/Profile_jenkins::Master/Profile_jenkins::Plugin[git]/Jenkins::Plugin[git]/File[/var/lib/jenkins/plugins/git.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /Stage[main]/Profile_jenkins::Master/Profile_jenkins::Plugin[git]/Jenkins::Plugin[git]/File[/var/lib/jenkins/plugins/git.hpi]/group: group changed 'root' to 'jenkins'
Notice: /Stage[main]/Profile_jenkins::Master/Profile_jenkins::Plugin[github]/Jenkins::Plugin[github]/File[/var/lib/j …
```
> Restore archive require

- lib/puppet_x/jenkins/provider/cli.rb
- manifests/cli.pp
- manifests/cli_helper.pp
Latest jenkins release is not accepting anymore the `-s` flag to use the cli as admin with an ssh key using the http api, we have to add the `-remoting` option to use this functionality.
> Added legacy functionality when using the `-s` flag in the jenkins cli

- spec/classes/jenkins_cli_spec.rb
- spec/unit/puppet_x/jenkins/provider/cli_spec.rb
In Jenkins 2.54, there was safer remoting enabled. In the process of this, the `-remoting` flag was added as part of CLI options. This is reflected in: https://github.com/jenkinsci/puppet-jenkins/pull/751. However, the relevant tests weren’t changed to reflect this.
This PR is a fix for that.
> Fix '-remoting' flag tests

- .travis.yml
- NATIVE_TYPES_AND_PROVIDERS.md
- README.md
- files/puppet_helper.groovy
- lib/puppet_x/jenkins/config.rb
- lib/puppet_x/jenkins/provider/cli.rb
- manifests/cli.pp
- manifests/cli/config.pp
- manifests/cli/exec.pp
- manifests/cli_helper.pp
- manifests/init.pp
- manifests/params.pp
- spec/acceptance/class_spec.rb
- spec/acceptance/job_spec.rb
- spec/acceptance/plugin_spec.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/classes/jenkins_cli_spec.rb
- spec/defines/jenkins_cli_exec_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/puppet_x/jenkins/provider/cli_spec.rb
This fixes #749 by adding support for the CLI introduced in jenkins 2.54 / 2.46.2 LTS 
https://issues.jenkins-ci.org/browse/JENKINS-41745
Also fixes #753 and some other test failues (like lint etc.)
> Fix https://github.com/jenkinsci/puppet-jenkins/issues/749

- .fixtures.yml
- metadata.json
Resolves multiple instances of this error message when executing spec
tests with under ruby 2.4 / puppet 4.10.6:
Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Resource type not found: Stdlib::Absolutepath
> bump stdlib min version to 4.18.0

- files/puppet_helper.groovy
This is the same fix as in https://github.com/jenkinsci/puppet-jenkins/commit/fcf3da8ce9e95c3b9ca48beb0a4adb3a00a0e4b6 but applied in another place in the file that assumed passphrase couldn't be null. (I checked, couldn't see anywhere else that would also need the same thing.)
> Support null passphrase when fetching credential_info

- manifests/init.pp
- manifests/params.pp
- spec/spec_helper_acceptance.rb
Archlinux provides it's own jenkins package. To use this module with Archlinux one has to set 'repo = false'. params.pp has been expanded to use correct values.
___
EDIT 20170627:
- params.pp: define 'repo' per osfamily. Distributions for which an official repository exists at pkg.jenkins.io define 'repo = true'. To use Archlinux own jenkin's package, 'repo = false' is set.
- init.pp: When 'repo = false' is set, a custom repository or the distribution's package will be installed. Documentation of this parameter was adjusted to describe this use case.
This way the jenkins module can be used with Archlinux. Other distributions can be added the same way. Default behavior was not changed.
> Add archlinux support

- README.md
This duplicates `metadata.json` and is out of date.
closes #799
> Remove dependencies section from README.

- metadata.json
Just a small dependency bump. Can't find any changes in the systemd 1.* series that might conflict with the use in this module.
> bump dependency on camptocamp/systemd

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
Looks like it might be a dependency issue since gitlab-plugin depends on new versions of everything.
> Add missing dependency to the gitlab plugin (credentials) test

- .travis.yml
There is no need to test against two Puppet 4.X versions.
> drop legacy puppet version from testmatrix

- manifests/repo/debian.pp
- spec/classes/jenkins_repo_debian_spec.rb
As per the puppetlabs/apt documentation, there should be a `notify => Exec['apt_update']` when defining repos using apt::sources, otherwise there is no guarantee that the packages in the new repo will be available the next time Apt tries to install a package.
> Run apt_update when defining debian repos

- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/type/jenkins_credentials.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
Extends the `credentials_list_json` method in the `puppet_helpers.groovy` script to support `com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials`.
> Add support for GoogleRobotPrivateKeyCredentials

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
Allow overriding the default Java command in jenkins-slave-defaults.erb (e.g. /etc/sysconfig/jenkins-slave).  This enables the use of a different Java version than the default system java.
n/a
> Allow custom location for slave JAVA command

- manifests/augeas.pp
Add the augeas parameter 'show_diff' to jenkins::augeas to be able to 'hide' diffs with credentials
> Add show_diff parameter to pass to augeas resource

- spec/acceptance/class_spec.rb
- spec/acceptance/plugin_spec.rb
- spec/acceptance/slave_spec.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/acceptance/xtypes/jenkins_job_spec.rb
- spec/spec_helper_acceptance.rb
This module has a large amount of acceptance code. And failing due to error on apply or due to  idempotency issue will trigger same message about failure with `works with no errors`.
The PR try to split as much as possible failing with messages:
* `works with no errors` : when fail is only due to error.
* `works idempotently` : when fail is only due to idempotency issue.
* `works with no errors and idempotently` : when i was unable to split.
> split examples about error and idempotency as much as possible

- manifests/config.pp
Latest stdlib (from git) has a new `merge` implementation.
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1008
It appears to be broken for puppet 4.  We're planning to drop puppet 4
any moment, but for right now, replacing the call to `merge` with `+`
works fine.
Fixes
```
Puppet::PreformattedError:
Evaluation Error: Error while evaluating a Function Call, 'merge' expects one of:
(Variant[Hash, Undef, String[0, 0]] args*)
rejected: parameter 'args' variant 0 entry 'notify' expects a value of type Undef or Data, got Type[Class]
rejected: parameter 'args' variant 1 expects a value of type Undef or String, got Struct
(Iterable args*, Callable[3, 3] block)
rejected: expects a block
(Iterable args*, Callable[2, 2] block)
rejected: expects a block at …
```
> Replace `merge` function with `+`

- metadata.json
Update urls and version numbers in the `metadata.json` file.
> Update metadata for Vox Pupuli release

- spec/spec_helper_acceptance.rb
This module is flapping (acceptance tests can pass or fail).
The second time this manifest is applyed 
```
class {'jenkins':
cli_remoting_free => true,
cli               => true,
}
```
the first action done is this `exec`:
https://github.com/voxpupuli/puppet-jenkins/blob/master/manifests/plugin.pp#L181
This exec without condition looks guilty. But it is probably due to content of custom fact `jenkins_plugins`
The goal of the PR is to permit to know the value of the custom fact and permit a check to know if value is as expect.
Edit :
For the moment i only saw an empty custom fact.
> add output of facter command to know value of custom fact

- manifests/config.pp
- manifests/init.pp
- manifests/user_setup.pp
- spec/classes/jenkins_user_setup_spec.rb
By splitting out the user creation, we can have a custom
localdir before the package (maybe) tries to create it or adjust it.
> Bugfix/custom localdir with user: Fixes #462

- manifests/repo.pp
- manifests/repo/debian.pp
- manifests/repo/el.pp
- manifests/repo/suse.pp
- spec/classes/jenkins_repo_spec.rb
See the individual commits for details:
* Simplify repository handling for distros
* Use contain over anchors
* Rely on puppetlabs-apt $notify_update
* Rely on puppetlabs-apt for apt-transport-https
* Use assert_private() from stdlib
* Do not include the stdlib class
> Refactor repository handling

- manifests/cli.pp
- manifests/cli/config.pp
- manifests/cli/reload.pp
We sometimes run into issues where the fixed "tries 10, try_sleep: 2" on the safe-restart-jenkins isn't enough, which causes the puppetrun to fail.
We would like to be able to configure it more. There's already a cli_tries and cli_try_sleep available that fits our use case, so I reused that one.
> Use variables for tries and try_sleep everywhere instead of hardcoding

- README.md
Updates module name references from `rtyler/jenkins` to `puppet/jenkins` in the README.
Fixes #934
> Update references to rtyler/jenkins

- manifests/plugin.pp
If $mananage_service => false, then the jenkins::service class doesn't exist. In 65363b69b54e1aa37e5821b0e94357de3af9c4f0 this was fixed via $notify, but one instance was missed.
> Fix a reference to jenkins::service

- manifests/init.pp
- spec/classes/jenkins_spec.rb
532242964375efc1013ba186f201ecbd74de0b36 changed the default from undef to false which means this code could never be hit again. Because the actual check was incorrect the tests never showed this.
> Remove redundant code

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
This doesn't fix all tests, but at least brings us a bit closer to working builds.
> Fix broken acceptance tests

- NATIVE_TYPES_AND_PROVIDERS.md
- README.md
- lib/puppet/x/jenkins/config.rb
- lib/puppet/x/jenkins/provider/cli.rb
- manifests/cli/config.pp
- manifests/init.pp
- spec/acceptance/class_spec.rb
- spec/acceptance/job_spec.rb
- spec/acceptance/plugin_spec.rb
- spec/classes/jenkins_cli_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/puppet/x/jenkins/provider/cli_spec.rb
Jenkins 2.54 was released in 2017, which is long EOL. Current versions have even dropped support for the old remoting.
> Drop code old CLI remoting support

- README.md
- examples/job-configuration/build.pp
- manifests/job.pp
- manifests/job/present.pp
- spec/acceptance/job_spec.rb
9ef227e97806ba387ba2b9ea82e0ac543376415a deprecated this and made it a noop. This removes the support.
> Remove deprecated enabled parameter on job

- metadata.json
With Puppet 5 EoL and Puppet 7 out, I figured it was time to bump metadata.json too.
> Change supported Puppet versions to 6 & 7

- templates/jenkins-slave-run.erb
Quoting OTHER_ARGS breaks usage of the `jenkins::slave::swarm_client_args` parameter when more than 1 argument is needed.
It's very similar to #940.
> Fix slave run with additional swarm arguments provided

- spec/classes/jenkins_service_spec.rb
- spec/classes/jenkins_slave_spec.rb
In 5bd3da4fc990095ab6cc244a241e7761fa8143f4 support for EL6 was dropped, but the tests weren't dropped.
Fixes: 5bd3da4fc990095ab6cc244a241e7761fa8143f4
> Drop EL6 tests

- lib/puppet/provider/jenkins_credentials/cli.rb
Unparseable JSON may still contain valid credentials or other sensitive data that should not be added to logs in plaintext.
Remove the variable that possibly contains sensitive data from the error message when parsing fails.
n/a
> Don't put unparseable JSON in output

- metadata.json
puppetlabs-java latest has dropped this and it's EOL anyway.
> Drop Ubuntu 16.04 support

- manifests/init.pp
- manifests/user_setup.pp
- spec/classes/jenkins_config_spec.rb
- templates/jenkins-override.epp
Currently the Systemd drop-in file can only override environment variables.
I would like to expand this functionality to make it possible to override every configuration in the **[Service]** section of the drop-in file.
Fixes #1009
> Drop-in file systemd configuration

- spec/acceptance/hieradata/common.yaml
- spec/acceptance/hieradata/os/RedHat.yaml
Jenkins 2.361.1 requires Java 11 or newer and breaks with Java 1.8.
> Install Java 11 on Red Hat OSes

- .github/workflows/ci.yml
- .sync.yml
- Gemfile
- spec/setup_acceptance_node.pp
- spec/spec_helper.rb
- spec/unit/facter/plugins_spec.rb
- spec/unit/jenkins_plugins_spec.rb
- spec/unit/jenkins_spec.rb
- spec/unit/puppet/type/jenkins_job_spec.rb
The service is now a native systemd service so there is no pidfile to be tracked. This means we can test on EL8 again.
> Remove PIDFile workaround and deprecated code

- manifests/job.pp
This is passed to `template()` which accepts relative paths.
Fixes #768
> Allow template to be a string

- spec/acceptance/xtypes/jenkins_job_spec.rb
- the plugin now requires `ionicons-api`, so install it
- pin to 6.897.vb_943ea_6b_a_08b_ as newer versions are not compatible with Jenkins LTS releases
> fix cloudbees-folder CI

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
> fix ssh-credentials and aws-credentials CI

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
> Credential plugins CI fixes

- manifests/plugin.pp
This allows forcing HTTP 1.1 per [official suggestion](https://github.com/jenkins-infra/helpdesk/issues/3078#issuecomment-1198084336), since HTTP 2 regularly fails when downloading.
> Add download option to jenkins module

- .sync.yml
- Gemfile
- NATIVE_TYPES_AND_PROVIDERS.md
- lib/puppet/feature/retries.rb
- lib/puppet/x/jenkins/config.rb
- lib/puppet/x/jenkins/provider/cli.rb
- manifests/cli/config.pp
- spec/classes/cli/config_spec.rb
- spec/unit/puppet/x/jenkins/config_spec.rb
- spec/unit/puppet/x/jenkins/provider/cli_spec.rb
- spec/unit/puppet/x/spec_jenkins_providers.rb
Retries is only used by the CLI providers. Puppet itself also provides retry functionality. This avoids the need to ensure a gem is installed in the right environment, which may not even work if it's a disconnected environment.
This does ignore a parameter for the maximum time to sleep. I'm looking for feedback on how to best deal with this.
> Use native Puppet instead of the retries Gem in the CLI provider, replacing try_sleep parameter by exponential backoff

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
2.440 is the latest LTS Jenkins, but newer workflow-job versions need
2.454+
> pin workflow-job plugin to a version compatible with Jenkins LTS

- metadata.json
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
Both are soonish EoL so we should drop them.
> CentOS: Drop EoL 7/8 support

- manifests/repo/debian.pp
- metadata.json
> Support puppetlabs/apt 10.x; require >= 9.2

- spec/acceptance/hieradata/common.yaml
- spec/acceptance/hieradata/family/Debian.yaml
- spec/acceptance/hieradata/family/RedHat.yaml
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
Jenkins 2.479.1 requires Java 17 or newer and breaks with Java 11
> Install Java 17 JDK in acceptance tests

- manifests/plugin.pp
- metadata.json
> Drop EoL EL7 support
