voxpupuli/puppet-jenkins

- files/puppet_helper.groovy
> set_security() does not save jenkins state

- files/puppet_helper.groovy
This is based off of some of @damoxc's work
References #385
> Avoid referring to class objects directly in the Groovy helper

- spec/defines/jenkins_plugin_spec.rb
> Add a simple rspec-puppet test to verify changing jenkins::plugin's timeout

- manifests/job.pp
- manifests/job/present.pp
- spec/defines/jenkins_job_spec.rb
> Minor clean up of difftool patch

- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/type/jenkins_credentials.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
Support FileCredentialsImpl credentials type with jenkins_credentials.
> Support FileCredentialsImpl in jenkins_credentials native type

- Rakefile
- manifests/cli_helper.pp
- manifests/init.pp
- spec/classes/jenkins_cli_helper_spec.rb
Fixes linter error and closes #420 .
> Rtyler 417 cleanup cli helper

- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
- spec/classes/jenkins_service_spec.rb
> Updated for RedHat systemd systems to use redhat provider until PUP-5353 is fixed

- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/type/jenkins_credentials.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
Reverts jenkinsci/puppet-jenkins#467
> Revert "Support FileCredentialsImpl in jenkins_credentials native type"

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
Need for setting memory, etc on java VM for slaves.
> add ability to set java_args on slaves

- manifests/init.pp
- manifests/params.pp
- spec/classes/jenkins_spec.rb
> Revert the parts of 00a90d4d that make no sense (fixes #474) (2nd attempt)

- manifests/augeas.pp
- spec/defines/jenkins_augeas_spec.rb
Helps with the configuration of a plugin and reloads (or restarts) jenkins after config changes.
> An augeas helper define to deal with configs

- files/puppet_helper.groovy
I adjusted the puppet_helper to configure Active Directory as a security realm.
> Use Active Directory realm as type

- .travis.yml
- Rakefile
- spec/acceptance/nodesets/centos-6-docker.yml
* Adds CentOS 6 Beaker docker file
* Adds travis matrix entry to run beaker-docker tests
> Adds Beaker docker testing to .travis.yml

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
Corrected Slave Dependency with when manage_slave_user is false and manage_client_jar is true
> Dependency correction when manage_slave_user is false

- manifests/plugin.pp
- spec/defines/jenkins_plugin_spec.rb
This PR is based on top of #516 and should be rebased after it is merged.
resolves #512
related to (but does not fix) #465
> cleanup existing plugin archive if extension changes

- Gemfile
- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/type/jenkins_credentials.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/spec_helper_acceptance.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
> add StringCredentialsImpl support to jenkins_credentials

- spec/acceptance/xtypes/jenkins_job_spec.rb
Attempt to reduce horrendously slow travis runtime (currently ~45mins).
> skip pending beaker tests

- README.md
- manifests/init.pp
- manifests/params.pp
- spec/classes/jenkins_repo_debian_spec.rb
- spec/classes/jenkins_repo_el_spec.rb
- spec/classes/jenkins_repo_suse_spec.rb
> Kludge around jenkins 2.x landing in the 'latest' repos

- files/puppet_helper.groovy
> Fix for groovy.lang.MissingPropertyException

- manifests/job.pp
- manifests/job/present.pp
- manifests/slave.pp
- spec/acceptance/job_spec.rb
- spec/defines/jenkins_job_spec.rb
Removing 'enable' statement on job.pp and job/present.pp which are breaking idempotence
> Removing 'enable' statement on job.pp and job/present.pp

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
Mostly so I can add the slave user to the docker group
> Allow groups to be set for the jenkins-slave user

- files/puppet_helper.groovy
> Fix syntax for class load of hudson.tasks.Mailer$UserProperty

- manifests/job/present.pp
- spec/acceptance/xtypes/jenkins_job_spec.rb
- spec/defines/jenkins_job_present_spec.rb
- spec/defines/jenkins_job_spec.rb
Give users the possibility to perform dynamic job configuration based on concat fragment and use them to create jobs within jenkins-cli
> Dynamic job configuration

- manifests/slave.pp
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
This is a rebase of #600 and I believe also resolves #632
> Add swarm client args string to support multiple arguments

- manifests/credentials.pp
- spec/defines/jenkins_credentials_spec.rb
This is a rebase and update of #587 to re-use existing CLI try/sleep parameters per @jhoblitt's original feedback
> Improve credentials definition idempotency

- files/puppet_helper.groovy
This is really just a rebase
Closes #580
> allow newline before start of private key

- lib/puppet/provider/jenkins_authorization_strategy/cli.rb
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/provider/jenkins_job/cli.rb
- lib/puppet/provider/jenkins_security_realm/cli.rb
- lib/puppet/provider/jenkins_user/cli.rb
- lib/puppet_x/jenkins/provider/cli.rb
> require JSON module -- rebase of #565

- files/puppet_helper.groovy
- manifests/security.pp
rebase/removal of gem addition of #674 
closes #674
resolves #673
> fix security setting idempotentance

- manifests/plugin.pp
rebase/edit of #672
resolves #668
closes #672
> workaround voxpupuli/puppet-archive#242

- metadata.json
> change apt module >= 2.1.0

- templates/jenkins-slave-run.erb
> fix slave auth broken by #710

- spec/acceptance/slave_spec.rb
- templates/jenkins-slave-run.erb
Regression introduced by \#719
> fix multiple slave labels

- manifests/init.pp
- spec/defines/jenkins_plugin_spec.rb
https://issues.jenkins-ci.org/browse/INFRA-1060
> Provide a way to override default_plugins_host for all plugins at one time

- manifests/init.pp
- manifests/params.pp
- spec/defines/jenkins_plugin_spec.rb
> update update-center base URL

- lib/puppet/jenkins/facts.rb
- lib/puppet/jenkins/plugins.rb
- lib/puppet/provider/jenkins_authorization_strategy/cli.rb
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/provider/jenkins_job/cli.rb
- lib/puppet/provider/jenkins_num_executors/cli.rb
- lib/puppet/provider/jenkins_security_realm/cli.rb
- lib/puppet/provider/jenkins_slaveagent_port/cli.rb
- lib/puppet/provider/jenkins_user/cli.rb
- lib/puppet/type/jenkins_authorization_strategy.rb
- lib/puppet/type/jenkins_credentials.rb
- lib/puppet/type/jenkins_job.rb
- lib/puppet/type/jenkins_num_executors.rb
- lib/puppet/type/jenkins_security_realm.rb
- lib/puppet/type/jenkins_slaveagent_port.rb
- lib/puppet/type/jenkins_user.rb
- lib/puppet_x/jenkins/config.rb
- lib/puppet_x/jenkins/provider.rb
- lib/puppet_x/jenkins/provider/cli.rb
- lib/puppet_x/jenkins/type.rb
- lib/puppet_x/jenkins/type/cli.rb
- lib/puppet_x/jenkins/util.rb
See: https://tickets.puppetlabs.com/browse/SERVER-973 for more
information
> Fix all require statements for files in puppet_x

- files/puppet_helper.groovy
in case key was created with empty passphrase
> Avoid getting plainText from null passphrase 

- manifests/cli.pp
- spec/acceptance/class_spec.rb
> Fix https://github.com/jenkinsci/puppet-jenkins/issues/744 by setting mode explicitly

- manifests/repo/debian.pp
This also closes pr #444 and some minor puppet-lint warnings.
> Fixes apt module deprecation warnings

- .travis.yml
> update travis matrix

- manifests/plugin.pp
- spec/acceptance/nodesets/centos-7-docker.Dockerfile
- spec/acceptance/plugin_spec.rb
Rebase of #734 on current master
Closes #734
> remove jenkins plugin dir before upgrade

- manifests/augeas.pp
- manifests/cli/config.pp
- manifests/cli/exec.pp
- manifests/cli_helper.pp
- manifests/credentials.pp
- manifests/direct_download.pp
- manifests/init.pp
- manifests/job.pp
- manifests/job/absent.pp
- manifests/job/present.pp
- manifests/master.pp
- manifests/plugin.pp
- manifests/security.pp
- manifests/slave.pp
- manifests/sysconfig.pp
- manifests/systemd.pp
- manifests/user.pp
- spec/classes/cli/config_spec.rb
- spec/classes/jenkins_security_spec.rb
- spec/classes/jenkins_slave_spec.rb
- spec/classes/jenkins_spec.rb
- spec/defines/jenkins_augeas_spec.rb
- spec/defines/jenkins_cli_exec_spec.rb
- spec/defines/jenkins_plugin_spec.rb
Rebase of #742 on current master
Closes #742
> Replace legacy validate_* calls with puppet4 datatypes

- manifests/repo/debian.pp
- manifests/repo/el.pp
- manifests/repo/suse.pp
- spec/classes/jenkins_repo_debian_spec.rb
- spec/classes/jenkins_repo_el_spec.rb
- spec/classes/jenkins_repo_suse_spec.rb
Rebase of #771 on current master
Closes #771
> Switch repositories to HTTPs to take advantage of end-to-end TLS

- metadata.json
> fix archive type not failing on HTTP 404s

- .gitignore
- metadata.json
> allow newer puppetlabs-java version

- .fixtures.yml
- metadata.json
- spec/spec_helper_acceptance.rb
> change zypprepo dependency to voxpupuli

- NATIVE_TYPES_AND_PROVIDERS.md
- files/puppet_helper.groovy
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/type/jenkins_credentials.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
This PR reimplements the functionality introduced by @matez's work in #467 and adds AWS and GitLab credentials.
> GitLab, AWS, and File credentials

- README.md
https://github.com/voxpupuli/puppet-jenkins/issues/828
> [828] Change badge url after transferring the repo to voxpopuli

- spec/acceptance/xtypes/jenkins_credentials_spec.rb
to avoid the random beaker test failures described in : https://github.com/voxpupuli/puppet-jenkins/issues/839
> add pending to AWSCredentialsImpl and GitLabApiTokenImpl

- examples/FreeBSD.pp
- examples/OpenBSD.pp
- examples/RHEL5.pp
- examples/job-configuration/build.pp
This got cherry-picked from https://github.com/voxpupuli/puppet-jenkins/pull/863
> puppet-lint: autofix

- .travis.yml
- Gemfile
- metadata.json
- spec/spec_helper.rb
This got cherrypicked from https://github.com/voxpupuli/puppet-jenkins/pull/863
> partial modulesync 1.9.2

- templates/jenkins-slave-defaults.erb
Fixing a typo found in templates/jenkins-slave-defaults.erb
n/a
> Fix small typo in jenkins-slave-defaults.erb

- manifests/slave.pp
> Replace is_array with Puppet 4 native comparision

- files/puppet_helper.groovy
- lib/puppet/provider/jenkins_credentials/cli.rb
- lib/puppet/type/jenkins_credentials.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
- spec/unit/puppet/provider/jenkins_credentials/cli_spec.rb
- spec/unit/puppet/type/jenkins_credentials_spec.rb
Add support for browserstack credentials
> Add browserstack credentials support

- metadata.json
> Adding SLES to supported platforms

- manifests/cli.pp
- manifests/job/present.pp
- manifests/plugin.pp
- manifests/sysconfig.pp
- spec/classes/jenkins_master_spec.rb
- spec/defines/jenkins_job_present_spec.rb
> fix unreferenced variables; add puppet5/6 support

- CHANGELOG.md
- HISTORY.md
- metadata.json
> release 2.0.0

- manifests/cli.pp
- manifests/cli/reload.pp
- manifests/config.pp
- manifests/direct_download.pp
- manifests/firewall.pp
- manifests/jobs.pp
- manifests/package.pp
- manifests/plugins.pp
- manifests/proxy.pp
- manifests/repo.pp
- manifests/repo/debian.pp
- manifests/repo/el.pp
- manifests/repo/suse.pp
- manifests/service.pp
- manifests/systemd.pp
- manifests/users.pp
- metadata.json
- spec/classes/jenkins_repo_debian_spec.rb
This reuses functionality from other modules rather than reinventing it.
> Rely more on stdlib and apt modules

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
- manifests/augeas.pp
- manifests/cli.pp
- manifests/cli/exec.pp
- manifests/cli/reload.pp
- manifests/cli_helper.pp
- manifests/config.pp
- manifests/credentials.pp
- manifests/direct_download.pp
- manifests/init.pp
- manifests/job/absent.pp
- manifests/job/present.pp
- manifests/jobs.pp
- manifests/package.pp
- manifests/plugin.pp
- manifests/proxy.pp
- manifests/repo.pp
- manifests/slave.pp
- manifests/sysconfig.pp
- manifests/user_setup.pp
- manifests/users.pp
- spec/spec_helper.rb
> modulesync 2.8.0

- README.md
Changes the recommended website for generating UUIDs to an open source website. Also link directly to UUID v4 generator for random UUIDs.
> Switch to open source UUID generator

- manifests/init.pp
The service should only be managed when the service is managed, otherwise the notify fails.
> Respect manage_service with Jenkins::Systemd[Jenkins]

- examples/plugin-configuration/git.pp
- manifests/augeas.pp
- manifests/plugin.pp
- spec/defines/jenkins_augeas_spec.rb
See individual commits for the specific changes.
> Remove params from jenkins::plugin and make it lint clean

- files/puppet_helper.groovy
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
This is entirely untested and I've never used this plugin, but I want to get rid of the pending tests.
> Implement ConduitCredentialsImpl in groovy_helper

- metadata.json
Update allowed puppetlabs/java module version to < 8.0.0
None
> update dependency puppetlabs-java to support < 8.0.0

- manifests/slave.pp
> puppet-lint: fix top_scope_facts warnings

- metadata.json
this also contains:
* https://github.com/voxpupuli/puppet-jenkins/pull/1010
* https://github.com/voxpupuli/puppet-jenkins/pull/1014
* https://github.com/voxpupuli/puppet-jenkins/pull/1015
* https://github.com/voxpupuli/puppet-jenkins/pull/1016
> camptocamp/systemd: Allow 3.x

- metadata.json
this also contains https://github.com/voxpupuli/puppet-jenkins/pull/1010
> puppetlabs/stdlib: allow 7.x

- metadata.json
this also contains:
* https://github.com/voxpupuli/puppet-jenkins/pull/1010
* https://github.com/voxpupuli/puppet-jenkins/pull/1014
> puppetlabs/apt: allow 8.x

- metadata.json
this also contains:
* https://github.com/voxpupuli/puppet-jenkins/pull/1010
* https://github.com/voxpupuli/puppet-jenkins/pull/1014
* https://github.com/voxpupuli/puppet-jenkins/pull/1015
> puppet/zypprepo: Allow 3.x & 4.x

- manifests/augeas.pp
- manifests/cli/config.pp
- spec/classes/jenkins_repo_debian_spec.rb
- spec/classes/jenkins_repo_suse_spec.rb
- spec/classes/jenkins_service_spec.rb
This is found by the optional_default check.
> Remove Optional[] where the param has a default

- lib/facter/jenkins.rb
- manifests/init.pp
- manifests/params.pp
- spec/classes/jenkins_service_spec.rb
- templates/jenkins-run.erb
- templates/jenkins.service.erb
Hello,
This PR add a new fact for the jenkins version and daemon param.
Define a systemd type param (forking or simple)
Actually no spec is add in the systemd content, I can add a unit test for that if you want.
https://github.com/voxpupuli/puppet-jenkins/issues/1024
> add version fact and daemon param for systemd unit file

- manifests/augeas.pp
- manifests/cli.pp
- manifests/cli_helper.pp
- manifests/credentials.pp
- manifests/job.pp
- manifests/security.pp
- manifests/user.pp
This isn't complete, but it makes progress.
> More puppet-strings conversion

- files/puppet_helper.groovy
- manifests/params.pp
- spec/acceptance/hieradata/os/RedHat.yaml
- spec/acceptance/plugin_spec.rb
- spec/acceptance/xtypes/jenkins_credentials_spec.rb
This fixes https://github.com/voxpupuli/puppet-jenkins/pull/1053 and also some other things that have broken by now.
> Install Java 11 JDK on Red Hat OSes

- manifests/slave.pp
- spec/acceptance/slave_spec.rb
- spec/classes/jenkins_slave_spec.rb
- templates/jenkins-slave-defaults.erb
Replaces https://github.com/voxpupuli/puppet-jenkins/pull/992
> Remove deprecated hiera_array usage

- .github/workflows/ci.yml
- .msync.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 5.4.0

- manifests/repo.pp
- manifests/repo/el.pp
Added a toggle to enable the repo in EL
> el repo enabled toggle added

- manifests/repo.pp
- manifests/repo/debian.pp
Update Debian repository key
See https://www.jenkins.io/doc/upgrade-guide/2.387/#upgrading-to-jenkins-lts-2-387-2
Note that this is really not related to 2.387.2 specifically since the whole stable repo is signed by the new key.
> Update Debian repository key for 2023

- metadata.json
> Drop Ubuntu 18.04, add 20.04 and 22.04 support

- metadata.json
> Add support for EL9, document Alma/Oracle/Rocky support

- metadata.json
> Add support for puppetlabs/java 11.x

- .fixtures.yml
> fixtures.yml: remove puppet version contraint

- metadata.json
> Add support for Puppet 8

- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/release.yml
- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/release.yml
- .msync.yml
- .overcommit.yml
- .puppet-lint.rc
- .rspec
- .rspec_parallel
- Gemfile
- spec/spec_helper.rb
> modulesync 9.1.0

- metadata.json
> Add support for Debian 12

- metadata.json
> Drop support for Ubuntu 20.04

- README.md
Update liberian-puppet url in README.md
Updates the link so users can easily access the new home of liberian-puppet.
> Update librarian-puppet url in README.md
